#!/usr/bin/python3
# -*- coding: utf-8 -*-

import sys
import math

def print_help():
    print("USAGE")
    print("\t./103cipher message key flag")
    print("\n\nDESCRIPTION")
    print("\tmessage\ta message, made of ASCII characters")
    print("\tkey\tthe encryption key, made of ASCII characters")
    print("\tflag\t0 for the message to be encrypted, 1 to be decrypted")

def colo_matrix(a):
    size = 0
    for col_index in range(len(a)):
        size = size + 1
    return size

def product_matrix(a,b):
    if colo_matrix(a) != len(b):
        return None
    output_list = []

    temp_row = len(b[0] * [0])
    for i in range(len(a)):
        output_list.append(temp_row[:])
    for row_index in range(len(a)):
        for col_index in range(len(b[0])):
            sum = 0
            for k in range(len(a[0])):
                sum = sum + a[row_index][k] * b[k][col_index]
        output_list[row_index][col_index] = sum
    return output_list

def display_key_matrix(arg):
    len_key = len(arg)
    i = 0
    size = 0
    j = 0
    r = 0
    s = 0

    while size * size < len_key :
        size = size + 1

    key_matrix = [0] * (size)
    for s in range (size) :
        key_matrix[s] = [0] * size

    print("Key matrix:")

    while j != n * n :
        while r < n - 1 :
            print("%i\t"%key_matrice[j], end = "")
            r = r + 1
            j = j + 1
        r = 0
        print("%i\n"%key_matrice[j], end = "")
        j = j + 1

def message_matrix(mes, key):
    len_mes = len(mes)
    len_key = len(key)
    i = 0
    j = 0
    r = 0
    size = 0

    while size * size < len_key :
        size = size + 1

    matrix_size = int((len_mes / size) + 1)
    mes_matrix = [0] * (size * matrix_size)

    while i != len_mes :
        mes_matrix[i] = ord(mes[i])
        i = i + 1

    return mes_matrix

def error ():
    if len(sys.argv) < 1 :
        print("not enough arguments")
        sys.exit(84)
    if sys.argv.__contains__("-h"):
        print_help()
        sys.exit(0)

def main():
    error()
    diplay_key_matrix(sys.argv[2])
    a = key_matrix(sys.argv[2])
    b = message_matrix(sys.argv[1], sys.argv[2])
    print("%d", product_matrix(a,b))
    #product_matrix(a, b)

main()
